CMTPATH=/junofs/users/huyuxiang/juno_centos7_v2/offline:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface
CMT_tag=$(tag)
CMTROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-branch/ExternalLibs/CMT/v1r26
CMT_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-branch/ExternalLibs/CMT/v1r26
CMTVERSION=v1r26
CMT_offset=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-branch/ExternalLibs
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/junofs/users/huyuxiang/juno_centos7_v2/offline/InstallArea/${CMTCONFIG}/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/InstallArea/${CMTCONFIG}/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/InstallArea/${CMTCONFIG}/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-branch/ExternalLibs/CMT/v1r26/${CMTBIN}:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/frontier/2.8.20/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/pacparser/1.3.7/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/podio/00-10/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-yaml/5.1.2/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/libyaml/0.2.2/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-cython/0.29.16/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/mysql-connector-cpp/1.1.8/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/mysql-connector-c/6.1.9/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/libmore/0.8.3/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Geant4/10.04.p02/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/HepMC/2.06.09/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/ROOT/6.20.02/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/xrootd/4.10.0/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/CLHEP/2.4.1.0/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/tbb/2019_U8/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/sqlite3/3.29.0/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/fftw3/3.3.8/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/gsl/2.5/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Xercesc/3.2.2/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Cmake/3.17.0/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Boost/1.72.0/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Python/2.7.17/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/contrib/gcc/8.3.0/bin:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/contrib/binutils/2.28/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/hep_job.sl6/bin/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/cvmfs/container.ihep.ac.cn/bin/
CLASSPATH=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-branch/ExternalLibs/CMT/v1r26/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-std=c++11 -fPIC -pipe -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc78-gcc830
RootIOTools_tag=$(tag)
ROOTIOTOOLSROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOTools
RootIOTools_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOTools
ROOTIOTOOLSVERSION=v0
RootIOTools_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
RootIOTools_offset=RootIO
RootIOTools_project=offline
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperKernel
SniperKernel_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
SniperKernel_project=sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperPolicy
SniperPolicy_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
SniperPolicy_project=sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
Boost_tag=$(tag)
BOOSTROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/Boost
Boost_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface
Boost_offset=Externals
Boost_project=ExternalInterface
Python_tag=$(tag)
PYTHONROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/Python
Python_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface
Python_offset=Externals
Python_project=ExternalInterface
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_home=${JUNO_EXTLIB_Boost_HOME}
Boost_pysuffix=${BOOST_PYTHON_SUFFIX}
Boost_linkopts= -L$(Boost_home)/lib  -lboost_python$(Boost_pysuffix)  -lboost_filesystem -lboost_system 
includes= $(ppcmd)"$(RootIOTools_root)"  $(ppcmd)"$(srcdir)" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/InstallArea/include" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/InstallArea/include" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/junofs/users/huyuxiang/juno_centos7_v2/offline/InstallArea/python:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/InstallArea/python:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/InstallArea/python:/junofs/users/huyuxiang/juno_centos7_v2/offline/InstallArea/amd64_linux26/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/InstallArea/amd64_linux26/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/InstallArea/amd64_linux26/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-yaml/5.1.2/lib/python2.7/site-packages:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-cython/0.29.16/lib/python2.7/site-packages:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/ROOT/6.20.02/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/xrootd/4.10.0/lib64/python2.7/site-packages:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Python/2.7.17/lib/./python2.7/lib-dynload:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Python/2.7.17/lib/python2.7/site-packages
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
DataModelRelease_tag=$(tag)
DATAMODELRELEASEROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/DataModelRelease
DataModelRelease_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/DataModelRelease
DATAMODELRELEASEVERSION=v0
DataModelRelease_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
DataModelRelease_offset=DataModel
DataModelRelease_project=offline
BaseEvent_tag=$(tag)
BASEEVENTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/BaseEvent
BaseEvent_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/BaseEvent
BASEEVENTVERSION=v0
BaseEvent_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
BaseEvent_offset=DataModel
BaseEvent_project=offline
XmlObjDesc_tag=$(tag)
XMLOBJDESCROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/XmlObjDesc
XmlObjDesc_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/XmlObjDesc
XMLOBJDESCVERSION=v0
XmlObjDesc_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
XmlObjDesc_project=offline
xmlsrc=xml
ROOT_tag=$(tag)
ROOTROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/ROOT
ROOT_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/ROOT
ROOTVERSION=v0
ROOT_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface
ROOT_offset=Externals
ROOT_project=ExternalInterface
ROOT_home=${JUNO_EXTLIB_ROOT_HOME}
ROOT_cppflags=`root-config --cflags` -Wno-long-long 
ROOT_linkopts=`root-config --evelibs` `root-config --evelibs`  -lPyROOT 
rootcint="$(ROOT_home)/bin/rootcint"
XODflags= -n JM  -n JM  -n JM  -n JM  -n JM 
BaseEvent_dependencies= BaseEventObj2Doth  BaseEventDict  BaseEventxodsrc 
install_more_includes_dependencies= BaseEventObj2Doth  ElecEventObj2Doth  RecEventObj2Doth  CalibEventObj2Doth  PhyEventObj2Doth 
BaseEventDict_dependencies= BaseEventObj2Doth  install_more_includes 
BaseEventxodsrc_dependencies= BaseEventObj2Doth 
BaseEvent_linkopts= -lBaseEvent 
BaseEvent_stamps=${BASEEVENTROOT}/${BINDIR}/BaseEvent.stamp 
BaseEvent_linker_library=BaseEvent
GenEventV2_tag=$(tag)
GENEVENTV2ROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/GenEventV2
GenEventV2_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/GenEventV2
GENEVENTV2VERSION=v0
GenEventV2_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
GenEventV2_offset=DataModel
GenEventV2_project=offline
EDMUtil_tag=$(tag)
EDMUTILROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/EDMUtil
EDMUtil_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/EDMUtil
EDMUTILVERSION=v0
EDMUtil_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
EDMUtil_offset=DataModel
EDMUtil_project=offline
EDMUtil_dependencies= EDMUtilDict  EDMUtilDict  EDMUtilDict  EDMUtilDict 
EDMUtilDict_dependencies= EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes 
EDMUtil_linkopts= -lEDMUtil 
EDMUtil_stamps=${EDMUTILROOT}/${BINDIR}/EDMUtil.stamp 
EDMUtil_linker_library=EDMUtil
HepMC_tag=$(tag)
HEPMCROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/HepMC
HepMC_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/HepMC
HEPMCVERSION=v0
HepMC_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface
HepMC_offset=Externals
HepMC_project=ExternalInterface
HepMC_home=${JUNO_EXTLIB_HepMC_HOME}
HepMC_linkopts= -L $(HepMC_home)/lib -lHepMC 
HepMC_cppflags= -I$(HepMC_home)/include 
GenHeader_cintflags= -p  -I$(GENEVENTV2ROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT)  $(HepMC_cppflags) 
GenEvent_cintflags= -p  -I$(GENEVENTV2ROOT)  -I$(BASEEVENTROOT)  $(HepMC_cppflags) 
GenEventV2_dependencies= GenEventV2Dict 
GenEventV2Dict_dependencies= GenEventV2Obj2Doth  install_more_includes 
GenEventV2_linkopts= -lGenEventV2 
GenEventV2_stamps=${GENEVENTV2ROOT}/${BINDIR}/GenEventV2.stamp 
GenEventV2_linker_library=GenEventV2
SimEventV2_tag=$(tag)
SIMEVENTV2ROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/SimEventV2
SimEventV2_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/SimEventV2
SIMEVENTV2VERSION=v0
SimEventV2_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
SimEventV2_offset=DataModel
SimEventV2_project=offline
SimEventV2_cintflags= -I$(SIMEVENTV2ROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT) 
SimHeader_cintflags= $(SimEventV2_cintflags) 
SimPMTHit_cintflags= $(SimEventV2_cintflags) 
SimTrack_cintflags= $(SimEventV2_cintflags) 
SimEvent_cintflags= $(SimEventV2_cintflags) 
SimTTHit_cintflags= $(SimEventV2_cintflags) 
SimEventV2_dependencies= SimEventV2Dict  SimEventV2Dict  SimEventV2Dict  SimEventV2Dict  SimEventV2Dict 
SimEventV2Dict_dependencies= SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes 
SimEventV2_linkopts= -lSimEventV2 
SimEventV2_stamps=${SIMEVENTV2ROOT}/${BINDIR}/SimEventV2.stamp 
SimEventV2_linker_library=SimEventV2
test_SimEvent_write_dependencies=SimEventV2
test_SimEvent_read_dependencies=SimEventV2
ElecEvent_tag=$(tag)
ELECEVENTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ElecEvent
ElecEvent_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ElecEvent
ELECEVENTVERSION=v0
ElecEvent_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
ElecEvent_offset=DataModel
ElecEvent_project=offline
Context_tag=$(tag)
CONTEXTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/Context
Context_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/Context
CONTEXTVERSION=v0
Context_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
Context_offset=DataModel
Context_project=offline
Context_cintflags=  
Context_dependencies= ContextDict 
Context_linkopts= -lContext 
Context_stamps=${CONTEXTROOT}/${BINDIR}/Context.stamp 
Context_linker_library=Context
test_Context_write_dependencies=Context
test_Context_read_dependencies=Context
ElecEvent_cintflags=-I$(CMTINSTALLAREA)/include
ElecHeader_cintflags=-I$(CMTINSTALLAREA)/include
ElecFeeCrate_cintflags=-I$(CMTINSTALLAREA)/include
ElecFeeChannel_cintflags=-I$(CMTINSTALLAREA)/include
SpmtElecEvent_cintflags=-I$(CMTINSTALLAREA)/include
SpmtElecAbcBlock_cintflags=-I$(CMTINSTALLAREA)/include
SpmtElecSpecialWord_cintflags=-I$(CMTINSTALAREA)/include
SpmtElecDiscrWord_cintflags=-I$(CMTINSTALAREA)/include
WpElecEvent_cintflags=-I$(CMTINSTALLAREA)/include
ElecEvent_dependencies= ElecEventObj2Doth  ElecEventDict  ElecEventxodsrc 
ElecEventDict_dependencies= ElecEventObj2Doth  install_more_includes 
ElecEventxodsrc_dependencies= ElecEventObj2Doth 
ElecEvent_linkopts= -lElecEvent 
ElecEvent_stamps=${ELECEVENTROOT}/${BINDIR}/ElecEvent.stamp 
ElecEvent_linker_library=ElecEvent
RecEvent_tag=$(tag)
RECEVENTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/RecEvent
RecEvent_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/RecEvent
RECEVENTVERSION=v0
RecEvent_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
RecEvent_offset=DataModel
RecEvent_project=offline
CLHEP_tag=$(tag)
CLHEPROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/CLHEP
CLHEP_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface/Externals/CLHEP
CLHEPVERSION=v0
CLHEP_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface
CLHEP_offset=Externals
CLHEP_project=ExternalInterface
CLHEP_home=${JUNO_EXTLIB_CLHEP_HOME}
CLHEP_linkopts= -L${JUNO_EXTLIB_CLHEP_HOME}/lib -lCLHEP 
CLHEP_cppflags= `clhep-config --include` 
CLHEPDict_tag=$(tag)
CLHEPDICTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/Dict/CLHEPDict
CLHEPDict_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/Dict/CLHEPDict
CLHEPDICTVERSION=v0
CLHEPDict_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
CLHEPDict_offset=DataModel/Dict
CLHEPDict_project=offline
CLHEPDict_dependencies= CLHEPDictDict 
CLHEPDictDict_dependencies= CLHEPDictObj2Doth  install_more_includes 
CLHEPInc_cintflags= -I$(CLHEP_home)/include -p 
CLHEPDict_linkopts= -Wl,--no-as-needed  -lCLHEPDict  -Wl,--as-needed 
CLHEPDict_stamps=${CLHEPDICTROOT}/${BINDIR}/CLHEPDict.stamp 
CLHEPDict_linker_library=CLHEPDict
CDRecEvent_cintflags=-I$(CMTINSTALLAREA)/include
RecHeader_cintflags=-I$(CMTINSTALLAREA)/include  -I$(CLHEP_home)/include
RecTrack_cintflags=-I$(CMTINSTALLAREA)/include  -I$(CLHEP_home)/include
CDTrackRecEvent_cintflags=-I$(CMTINSTALLAREA)/include  -I$(CLHEP_home)/include
WPRecEvent_cintflags=-I$(CMTINSTALLAREA)/include  -I$(CLHEP_home)/include
TTRecEvent_cintflags=-I$(CMTINSTALLAREA)/include  -I$(CLHEP_home)/include
RecEvent_dependencies= RecEventObj2Doth  RecEventDict  RecEventxodsrc 
RecEventDict_dependencies= RecEventObj2Doth  install_more_includes 
RecEventxodsrc_dependencies= RecEventObj2Doth 
RecEvent_linkopts= -lRecEvent 
RecEvent_stamps=${RECEVENTROOT}/${BINDIR}/RecEvent.stamp 
RecEvent_linker_library=RecEvent
CalibEvent_tag=$(tag)
CALIBEVENTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/CalibEvent
CalibEvent_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/CalibEvent
CALIBEVENTVERSION=v0
CalibEvent_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
CalibEvent_offset=DataModel
CalibEvent_project=offline
CalibEvent_cintflags=-I$(CMTINSTALLAREA)/include
CalibHeader_cintflags=-I$(CMTINSTALLAREA)/include
TTCalibEvent_cintflags=-I$(CMTINSTALLAREA)/include
CalibEvent_dependencies= CalibEventObj2Doth  CalibEventDict  CalibEventxodsrc 
CalibEventDict_dependencies= CalibEventObj2Doth  install_more_includes 
CalibEventxodsrc_dependencies= CalibEventObj2Doth 
CalibEvent_linkopts= -lCalibEvent 
CalibEvent_stamps=${CALIBEVENTROOT}/${BINDIR}/CalibEvent.stamp 
CalibEvent_linker_library=CalibEvent
ClusterInfoEvent_tag=$(tag)
CLUSTERINFOEVENTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ClusterInfo/ClusterInfoEvent
ClusterInfoEvent_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ClusterInfo/ClusterInfoEvent
CLUSTERINFOEVENTVERSION=v0
ClusterInfoEvent_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
ClusterInfoEvent_offset=DataModel/ClusterInfo
ClusterInfoEvent_project=offline
ClusterInfoEvent_cintflags= -I$(CLUSTERINFOEVENTROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT) 
ClusterInfoHeader_cintflags= $(ClusterInfoEvent_cintflags) 
ClusterHitIdx_cintflags= $(ClusterInfoEvent_cintflags) 
ClusterHitCol_cintflags= $(ClusterInfoEvent_cintflags) 
ClusterInfoEvent_dependencies= ClusterInfoEventDict  ClusterInfoEventDict  ClusterInfoEventDict  ClusterInfoEventDict 
ClusterInfoEventDict_dependencies= ClusterInfoEventObj2Doth  install_more_includes  ClusterInfoEventObj2Doth  install_more_includes  ClusterInfoEventObj2Doth  install_more_includes  ClusterInfoEventObj2Doth  install_more_includes 
ClusterInfoEvent_linkopts= -lClusterInfoEvent 
ClusterInfoEvent_stamps=${CLUSTERINFOEVENTROOT}/${BINDIR}/ClusterInfoEvent.stamp 
ClusterInfoEvent_linker_library=ClusterInfoEvent
test_ClusterInfoEvent_write_dependencies=ClusterInfoEvent
test_ClusterInfoEvent_read_dependencies=ClusterInfoEvent
ClusterInfoSvc_tag=$(tag)
CLUSTERINFOSVCROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ClusterInfo/ClusterInfoSvc
ClusterInfoSvc_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ClusterInfo/ClusterInfoSvc
CLUSTERINFOSVCVERSION=v0
ClusterInfoSvc_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
ClusterInfoSvc_offset=DataModel/ClusterInfo
ClusterInfoSvc_project=offline
EvtNavigator_tag=$(tag)
EVTNAVIGATORROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/EvtNavigator
EvtNavigator_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/EvtNavigator
EVTNAVIGATORVERSION=v0
EvtNavigator_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
EvtNavigator_offset=DataModel
EvtNavigator_project=offline
EvtNavigator_cintflags= -I$(BASEEVENTROOT) -I$(EDMUTILROOT) 
EvtNavigator_dependencies= EvtNavigatorDict 
EvtNavigatorDict_dependencies= EvtNavigatorObj2Doth  install_more_includes 
EvtNavigator_linkopts= -lEvtNavigator 
EvtNavigator_stamps=${EVTNAVIGATORROOT}/${BINDIR}/EvtNavigator.stamp 
EvtNavigator_linker_library=EvtNavigator
DataRegistritionSvc_tag=$(tag)
DATAREGISTRITIONSVCROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/DataRegistritionSvc
DataRegistritionSvc_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/DataRegistritionSvc
DATAREGISTRITIONSVCVERSION=v0
DataRegistritionSvc_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
DataRegistritionSvc_offset=DataModel
DataRegistritionSvc_project=offline
DataRegistritionSvc_linkopts= -lDataRegistritionSvc 
DataRegistritionSvc_stamps=${DATAREGISTRITIONSVCROOT}/${BINDIR}/DataRegistritionSvc.stamp 
DataRegistritionSvc_linker_library=DataRegistritionSvc
Geometry_tag=$(tag)
GEOMETRYROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/Detector/Geometry
Geometry_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/Detector/Geometry
GEOMETRYVERSION=v0
Geometry_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
Geometry_offset=Detector
Geometry_project=offline
Identifier_tag=$(tag)
IDENTIFIERROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/Detector/Identifier
Identifier_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/Detector/Identifier
IDENTIFIERVERSION=v0
Identifier_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
Identifier_offset=Detector
Identifier_project=offline
Identifier_linkopts= -lIdentifier 
Identifier_stamps=${IDENTIFIERROOT}/${BINDIR}/Identifier.stamp 
Identifier_linker_library=Identifier
JUNO_GEOMETRY_PATH=/junofs/users/huyuxiang/juno_centos7_v2/offline/Detector/Geometry
Geometry_linkopts= -lGeometry 
Geometry_stamps=${GEOMETRYROOT}/${BINDIR}/Geometry.stamp 
Geometry_linker_library=Geometry
ClusterInfoSvc_linkopts= -lClusterInfoSvc 
ClusterInfoSvc_stamps=${CLUSTERINFOSVCROOT}/${BINDIR}/ClusterInfoSvc.stamp 
ClusterInfoSvc_linker_library=ClusterInfoSvc
PhyEvent_tag=$(tag)
PHYEVENTROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/PhyEvent
PhyEvent_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/PhyEvent
PHYEVENTVERSION=v0
PhyEvent_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
PhyEvent_offset=DataModel
PhyEvent_project=offline
PhyEvent_cintflags=-I$(CMTINSTALLAREA)/include
PhyHeader_cintflags=-I$(CMTINSTALLAREA)/include
PhyEvent_dependencies= PhyEventObj2Doth  PhyEventDict  PhyEventxodsrc 
PhyEventDict_dependencies= PhyEventObj2Doth  install_more_includes 
PhyEventxodsrc_dependencies= PhyEventObj2Doth 
PhyEvent_linkopts= -lPhyEvent 
PhyEvent_stamps=${PHYEVENTROOT}/${BINDIR}/PhyEvent.stamp 
PhyEvent_linker_library=PhyEvent
RootIOSvc_tag=$(tag)
ROOTIOSVCROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOSvc
RootIOSvc_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOSvc
ROOTIOSVCVERSION=v0
RootIOSvc_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
RootIOSvc_offset=RootIO
RootIOSvc_project=offline
RootIOUtil_tag=$(tag)
ROOTIOUTILROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOUtil
RootIOUtil_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOUtil
ROOTIOUTILVERSION=v0
RootIOUtil_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
RootIOUtil_offset=RootIO
RootIOUtil_project=offline
RootIOUtil_linkopts= -lRootIOUtil 
RootIOUtil_stamps=${ROOTIOUTILROOT}/${BINDIR}/RootIOUtil.stamp 
RootIOUtil_linker_library=RootIOUtil
RootIOSvc_linkopts= -lRootIOSvc 
RootIOSvc_stamps=${ROOTIOSVCROOT}/${BINDIR}/RootIOSvc.stamp 
RootIOSvc_linker_library=RootIOSvc
JunoTimer_tag=$(tag)
JUNOTIMERROOT=/junofs/users/huyuxiang/juno_centos7_v2/offline/Utilities/JunoTimer
JunoTimer_root=/junofs/users/huyuxiang/juno_centos7_v2/offline/Utilities/JunoTimer
JUNOTIMERVERSION=v0
JunoTimer_cmtpath=/junofs/users/huyuxiang/juno_centos7_v2/offline
JunoTimer_offset=Utilities
JunoTimer_project=offline
SniperRelease_tag=$(tag)
SNIPERRELEASEROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperRelease
SniperRelease_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperRelease
SNIPERRELEASEVERSION=v2
SniperRelease_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
SniperRelease_project=sniper
DataBuffer_tag=$(tag)
DATABUFFERROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperUtil/DataBuffer
DataBuffer_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperUtil/DataBuffer
DATABUFFERVERSION=v0
DataBuffer_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
DataBuffer_offset=SniperUtil
DataBuffer_project=sniper
HelloWorld_tag=$(tag)
HELLOWORLDROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/Examples/HelloWorld
HelloWorld_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/Examples/HelloWorld
HELLOWORLDVERSION=v1
HelloWorld_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
HelloWorld_offset=Examples
HelloWorld_project=sniper
PyDataStore_tag=$(tag)
PYDATASTOREROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperUtil/PyDataStore
PyDataStore_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperUtil/PyDataStore
PYDATASTOREVERSION=v0
PyDataStore_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
PyDataStore_offset=SniperUtil
PyDataStore_project=sniper
PyDataStore_linkopts= -lRootWriter 
PyDataStore_stamps=${PYDATASTOREROOT}/${BINDIR}/RootWriter.stamp 
PyDataStore_linker_library=RootWriter
RootWriter_tag=$(tag)
ROOTWRITERROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperSvc/RootWriter
RootWriter_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/SniperSvc/RootWriter
ROOTWRITERVERSION=v0
RootWriter_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
RootWriter_offset=SniperSvc
RootWriter_project=sniper
RootWriter_linkopts= -lRootWriter 
RootWriter_stamps=${ROOTWRITERROOT}/${BINDIR}/RootWriter.stamp 
RootWriter_linker_library=RootWriter
DummyAlg_tag=$(tag)
DUMMYALGROOT=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/Examples/DummyAlg
DummyAlg_root=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/Examples/DummyAlg
DUMMYALGVERSION=v0
DummyAlg_cmtpath=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
DummyAlg_offset=Examples
DummyAlg_project=sniper
JunoTimer_linkopts= -lJunoTimer 
JunoTimer_stamps=${JUNOTIMERROOT}/${BINDIR}/JunoTimer.stamp 
JunoTimer_linker_library=JunoTimer
RootIOTools_linkopts= -lRootIOTools 
RootIOTools_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(RootIOTools_use_linkopts)
RootIOTools_use_linkopts=    $(DataModelRelease_linkopts)  $(GenEventV2_linkopts)  $(SimEventV2_linkopts)  $(ElecEvent_linkopts)  $(RecEvent_linkopts)  $(ClusterInfoSvc_linkopts)  $(CalibEvent_linkopts)  $(ClusterInfoEvent_linkopts)  $(RootIOSvc_linkopts)  $(RootIOUtil_linkopts)  $(EvtNavigator_linkopts)  $(DataRegistritionSvc_linkopts)  $(PhyEvent_linkopts)  $(EDMUtil_linkopts)  $(Geometry_linkopts)  $(Identifier_linkopts)  $(JunoTimer_linkopts)  $(SniperRelease_linkopts)  $(DataBuffer_linkopts)  $(HelloWorld_linkopts)  $(PyDataStore_linkopts)  $(DummyAlg_linkopts)  $(RootWriter_linkopts)  $(SniperKernel_linkopts)  $(BaseEvent_linkopts)  $(CLHEPDict_linkopts)  $(Context_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts)  $(HepMC_linkopts)  $(CLHEP_linkopts) 
RootIOTools_stamps=${ROOTIOTOOLSROOT}/${BINDIR}/RootIOTools.stamp 
RootIOTools_linker_library=RootIOTools
tag=amd64_linux26
package=RootIOTools
version=v0
PACKAGE_ROOT=$(ROOTIOTOOLSROOT)
srcdir=../src
bin=../$(RootIOTools_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOTools/amd64_linux26/
project=offline
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(sniper_installarea_prefix)/$(CMTCONFIG)/lib $(sniper_installarea_prefix)/share/lib $(sniper_installarea_prefix)/share/bin $(mt.sniper_installarea_prefix)/$(CMTCONFIG)/lib $(mt.sniper_installarea_prefix)/share/lib $(mt.sniper_installarea_prefix)/share/bin $(offline_installarea_prefix)/$(CMTCONFIG)/lib $(offline_installarea_prefix)/share/lib $(offline_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(RootIOTools_linkopts)  $(DataModelRelease_linkopts)  $(GenEventV2_linkopts)  $(SimEventV2_linkopts)  $(ElecEvent_linkopts)  $(RecEvent_linkopts)  $(ClusterInfoSvc_linkopts)  $(CalibEvent_linkopts)  $(ClusterInfoEvent_linkopts)  $(RootIOSvc_linkopts)  $(RootIOUtil_linkopts)  $(EvtNavigator_linkopts)  $(DataRegistritionSvc_linkopts)  $(PhyEvent_linkopts)  $(EDMUtil_linkopts)  $(Geometry_linkopts)  $(Identifier_linkopts)  $(JunoTimer_linkopts)  $(SniperRelease_linkopts)  $(DataBuffer_linkopts)  $(HelloWorld_linkopts)  $(PyDataStore_linkopts)  $(DummyAlg_linkopts)  $(RootWriter_linkopts)  $(SniperKernel_linkopts)  $(BaseEvent_linkopts)  $(CLHEPDict_linkopts)  $(Context_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts)  $(HepMC_linkopts)  $(CLHEP_linkopts) 
ExternalInterface_installarea_prefix=$(cmt_installarea_prefix)
ExternalInterface_installarea_prefix_remove=$(ExternalInterface_installarea_prefix)
LD_LIBRARY_PATH=/junofs/users/huyuxiang/juno_centos7_v2/offline/InstallArea/${CMTCONFIG}/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/InstallArea/${CMTCONFIG}/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/InstallArea/${CMTCONFIG}/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/frontier/2.8.20/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/pacparser/1.3.7/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/podio/00-10/lib64:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-yaml/5.1.2/lib/python2.7/site-packages:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-yaml/5.1.2/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/libyaml/0.2.2/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-cython/0.29.16/lib/python2.7/site-packages:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/python-cython/0.29.16/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/mysql-connector-cpp/1.1.8/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/mysql-connector-c/6.1.9/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/libmore/0.8.3/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Geant4/10.04.p02/lib64:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/HepMC/2.06.09/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/ROOT/6.20.02/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/xrootd/4.10.0/lib64/python2.7/site-packages:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/xrootd/4.10.0/lib64:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/CLHEP/2.4.1.0/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/tbb/2019_U8/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/sqlite3/3.29.0/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/fftw3/3.3.8/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/gsl/2.5/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Xercesc/3.2.2/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Boost/1.72.0/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Python/2.7.17/lib/python2.7/site-packages:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Python/2.7.17/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/contrib/gcc/8.3.0/lib64:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/contrib/gcc/8.3.0/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/contrib/binutils/2.28/lib64:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/contrib/binutils/2.28/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-branch/ExternalLibs/CLHEP/2.4.1.0/lib:/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-branch/ExternalLibs/Xercesc/3.2.2/lib
sniper_installarea_prefix=$(cmt_installarea_prefix)
sniper_installarea_prefix_remove=$(sniper_installarea_prefix)
mt.sniper_installarea_prefix=$(cmt_installarea_prefix)
mt.sniper_installarea_prefix_remove=$(mt.sniper_installarea_prefix)
offline_installarea_prefix=$(cmt_installarea_prefix)
offline_installarea_prefix_remove=$(offline_installarea_prefix)
cmt_installarea_linkopts= -L/junofs/users/huyuxiang/juno_centos7_v2/offline/$(offline_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/$(mt.sniper_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/$(sniper_installarea_prefix)/$(CMTCONFIG)/lib 
ExternalInterface_home=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalInterface
sniper_home=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper
mt.sniper_home=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper
offline_home=/junofs/users/huyuxiang/juno_centos7_v2/offline
offline_install_include= /junofs/users/huyuxiang/juno_centos7_v2/offline/$(offline_installarea_prefix)/include 
mt.sniper_install_include= /cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/$(mt.sniper_installarea_prefix)/include 
sniper_install_include= /cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/$(sniper_installarea_prefix)/include 
sniper_python_path=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/$(sniper_installarea_prefix)/$(tag)/lib
mt.sniper_python_path=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/$(mt.sniper_installarea_prefix)/$(tag)/lib
offline_python_path=/junofs/users/huyuxiang/juno_centos7_v2/offline/$(offline_installarea_prefix)/$(tag)/lib
sniper_install_python=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/sniper/$(sniper_installarea_prefix)/python
mt.sniper_install_python=/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/mt.sniper/$(mt.sniper_installarea_prefix)/python
offline_install_python=/junofs/users/huyuxiang/juno_centos7_v2/offline/$(offline_installarea_prefix)/python
CMTINSTALLAREA=/junofs/users/huyuxiang/juno_centos7_v2/offline/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(DataModelRelease_root)/cmt/requirements $(GenEventV2_root)/cmt/requirements $(SimEventV2_root)/cmt/requirements $(ElecEvent_root)/cmt/requirements $(RecEvent_root)/cmt/requirements $(ClusterInfoSvc_root)/cmt/requirements $(CalibEvent_root)/cmt/requirements $(ClusterInfoEvent_root)/cmt/requirements $(RootIOSvc_root)/cmt/requirements $(RootIOUtil_root)/cmt/requirements $(EvtNavigator_root)/cmt/requirements $(DataRegistritionSvc_root)/cmt/requirements $(PhyEvent_root)/cmt/requirements $(EDMUtil_root)/cmt/requirements $(Geometry_root)/cmt/requirements $(Identifier_root)/cmt/requirements $(JunoTimer_root)/cmt/requirements $(SniperRelease_root)/cmt/requirements $(DataBuffer_root)/cmt/requirements $(HelloWorld_root)/cmt/requirements $(PyDataStore_root)/cmt/requirements $(DummyAlg_root)/cmt/requirements $(RootWriter_root)/cmt/requirements $(SniperKernel_root)/cmt/requirements $(BaseEvent_root)/cmt/requirements $(CLHEPDict_root)/cmt/requirements $(XmlObjDesc_root)/cmt/requirements $(Context_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(HepMC_root)/cmt/requirements $(CLHEP_root)/cmt/requirements 
use_includes= $(ppcmd)"$(DataModelRelease_root)/src" $(ppcmd)"$(GenEventV2_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/GenEventV2/" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/GenEventV2/Event" $(ppcmd)"$(SimEventV2_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/SimEventV2/" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/SimEventV2/Event" $(ppcmd)"$(ElecEvent_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ElecEvent/Event" $(ppcmd)"$(RecEvent_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/RecEvent/Event" $(ppcmd)"$(ClusterInfoSvc_root)/src" $(ppcmd)"$(CalibEvent_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/CalibEvent/Event" $(ppcmd)"$(ClusterInfoEvent_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ClusterInfo/ClusterInfoEvent/" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/ClusterInfo/ClusterInfoEvent/Event" $(ppcmd)"$(RootIOSvc_root)/src" $(ppcmd)"$(RootIOUtil_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/RootIO/RootIOUtil/RootIOUtil" $(ppcmd)"$(EvtNavigator_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/EvtNavigator/EvtNavigator" $(ppcmd)"$(DataRegistritionSvc_root)/src" $(ppcmd)"$(PhyEvent_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/PhyEvent/Event" $(ppcmd)"$(EDMUtil_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/EDMUtil/include" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/EDMUtil/EDMUtil" $(ppcmd)"$(Geometry_root)/src" $(ppcmd)"$(Identifier_root)/src" $(ppcmd)"$(JunoTimer_root)/src" $(ppcmd)"$(SniperRelease_root)/src" $(ppcmd)"$(DataBuffer_root)/src" $(ppcmd)"$(HelloWorld_root)/src" $(ppcmd)"$(PyDataStore_root)/src" $(ppcmd)"$(DummyAlg_root)/src" $(ppcmd)"$(RootWriter_root)/src" $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(BaseEvent_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/BaseEvent/Event" $(ppcmd)"$(CLHEPDict_root)/src" $(ppcmd)"$(Context_root)/src" $(ppcmd)"/junofs/users/huyuxiang/juno_centos7_v2/offline/DataModel/Context/Context" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/Boost/1.72.0/include" $(ppcmd)"$(Python_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/centos7_amd64_gcc830/Pre-Release/J20v2r0-Pre1/ExternalLibs/ROOT/6.20.02/include" $(ppcmd)"$(HepMC_root)/src" $(ppcmd)"$(CLHEP_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(RootIOTools_stamps)  $(DataModelRelease_stamps)  $(GenEventV2_stamps)  $(SimEventV2_stamps)  $(ElecEvent_stamps)  $(RecEvent_stamps)  $(ClusterInfoSvc_stamps)  $(CalibEvent_stamps)  $(ClusterInfoEvent_stamps)  $(RootIOSvc_stamps)  $(RootIOUtil_stamps)  $(EvtNavigator_stamps)  $(DataRegistritionSvc_stamps)  $(PhyEvent_stamps)  $(EDMUtil_stamps)  $(Geometry_stamps)  $(Identifier_stamps)  $(JunoTimer_stamps)  $(SniperRelease_stamps)  $(DataBuffer_stamps)  $(HelloWorld_stamps)  $(PyDataStore_stamps)  $(DummyAlg_stamps)  $(RootWriter_stamps)  $(SniperKernel_stamps)  $(BaseEvent_stamps)  $(CLHEPDict_stamps)  $(Context_stamps)  $(SniperPolicy_stamps)  $(Boost_stamps)  $(Python_stamps)  $(ROOT_stamps)  $(HepMC_stamps)  $(CLHEP_stamps) 
use_cflags=  $(RootIOTools_cflags)  $(DataModelRelease_cflags)  $(GenEventV2_cflags)  $(SimEventV2_cflags)  $(ElecEvent_cflags)  $(RecEvent_cflags)  $(ClusterInfoSvc_cflags)  $(CalibEvent_cflags)  $(ClusterInfoEvent_cflags)  $(RootIOSvc_cflags)  $(RootIOUtil_cflags)  $(EvtNavigator_cflags)  $(DataRegistritionSvc_cflags)  $(PhyEvent_cflags)  $(EDMUtil_cflags)  $(Geometry_cflags)  $(Identifier_cflags)  $(JunoTimer_cflags)  $(SniperRelease_cflags)  $(DataBuffer_cflags)  $(HelloWorld_cflags)  $(PyDataStore_cflags)  $(DummyAlg_cflags)  $(RootWriter_cflags)  $(SniperKernel_cflags)  $(BaseEvent_cflags)  $(CLHEPDict_cflags)  $(Context_cflags)  $(SniperPolicy_cflags)  $(Boost_cflags)  $(Python_cflags)  $(ROOT_cflags)  $(HepMC_cflags)  $(CLHEP_cflags) 
use_pp_cflags=  $(RootIOTools_pp_cflags)  $(DataModelRelease_pp_cflags)  $(GenEventV2_pp_cflags)  $(SimEventV2_pp_cflags)  $(ElecEvent_pp_cflags)  $(RecEvent_pp_cflags)  $(ClusterInfoSvc_pp_cflags)  $(CalibEvent_pp_cflags)  $(ClusterInfoEvent_pp_cflags)  $(RootIOSvc_pp_cflags)  $(RootIOUtil_pp_cflags)  $(EvtNavigator_pp_cflags)  $(DataRegistritionSvc_pp_cflags)  $(PhyEvent_pp_cflags)  $(EDMUtil_pp_cflags)  $(Geometry_pp_cflags)  $(Identifier_pp_cflags)  $(JunoTimer_pp_cflags)  $(SniperRelease_pp_cflags)  $(DataBuffer_pp_cflags)  $(HelloWorld_pp_cflags)  $(PyDataStore_pp_cflags)  $(DummyAlg_pp_cflags)  $(RootWriter_pp_cflags)  $(SniperKernel_pp_cflags)  $(BaseEvent_pp_cflags)  $(CLHEPDict_pp_cflags)  $(Context_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(ROOT_pp_cflags)  $(HepMC_pp_cflags)  $(CLHEP_pp_cflags) 
use_cppflags=  $(RootIOTools_cppflags)  $(DataModelRelease_cppflags)  $(GenEventV2_cppflags)  $(SimEventV2_cppflags)  $(ElecEvent_cppflags)  $(RecEvent_cppflags)  $(ClusterInfoSvc_cppflags)  $(CalibEvent_cppflags)  $(ClusterInfoEvent_cppflags)  $(RootIOSvc_cppflags)  $(RootIOUtil_cppflags)  $(EvtNavigator_cppflags)  $(DataRegistritionSvc_cppflags)  $(PhyEvent_cppflags)  $(EDMUtil_cppflags)  $(Geometry_cppflags)  $(Identifier_cppflags)  $(JunoTimer_cppflags)  $(SniperRelease_cppflags)  $(DataBuffer_cppflags)  $(HelloWorld_cppflags)  $(PyDataStore_cppflags)  $(DummyAlg_cppflags)  $(RootWriter_cppflags)  $(SniperKernel_cppflags)  $(BaseEvent_cppflags)  $(CLHEPDict_cppflags)  $(Context_cppflags)  $(SniperPolicy_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(ROOT_cppflags)  $(HepMC_cppflags)  $(CLHEP_cppflags) 
use_pp_cppflags=  $(RootIOTools_pp_cppflags)  $(DataModelRelease_pp_cppflags)  $(GenEventV2_pp_cppflags)  $(SimEventV2_pp_cppflags)  $(ElecEvent_pp_cppflags)  $(RecEvent_pp_cppflags)  $(ClusterInfoSvc_pp_cppflags)  $(CalibEvent_pp_cppflags)  $(ClusterInfoEvent_pp_cppflags)  $(RootIOSvc_pp_cppflags)  $(RootIOUtil_pp_cppflags)  $(EvtNavigator_pp_cppflags)  $(DataRegistritionSvc_pp_cppflags)  $(PhyEvent_pp_cppflags)  $(EDMUtil_pp_cppflags)  $(Geometry_pp_cppflags)  $(Identifier_pp_cppflags)  $(JunoTimer_pp_cppflags)  $(SniperRelease_pp_cppflags)  $(DataBuffer_pp_cppflags)  $(HelloWorld_pp_cppflags)  $(PyDataStore_pp_cppflags)  $(DummyAlg_pp_cppflags)  $(RootWriter_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(BaseEvent_pp_cppflags)  $(CLHEPDict_pp_cppflags)  $(Context_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(ROOT_pp_cppflags)  $(HepMC_pp_cppflags)  $(CLHEP_pp_cppflags) 
use_fflags=  $(RootIOTools_fflags)  $(DataModelRelease_fflags)  $(GenEventV2_fflags)  $(SimEventV2_fflags)  $(ElecEvent_fflags)  $(RecEvent_fflags)  $(ClusterInfoSvc_fflags)  $(CalibEvent_fflags)  $(ClusterInfoEvent_fflags)  $(RootIOSvc_fflags)  $(RootIOUtil_fflags)  $(EvtNavigator_fflags)  $(DataRegistritionSvc_fflags)  $(PhyEvent_fflags)  $(EDMUtil_fflags)  $(Geometry_fflags)  $(Identifier_fflags)  $(JunoTimer_fflags)  $(SniperRelease_fflags)  $(DataBuffer_fflags)  $(HelloWorld_fflags)  $(PyDataStore_fflags)  $(DummyAlg_fflags)  $(RootWriter_fflags)  $(SniperKernel_fflags)  $(BaseEvent_fflags)  $(CLHEPDict_fflags)  $(Context_fflags)  $(SniperPolicy_fflags)  $(Boost_fflags)  $(Python_fflags)  $(ROOT_fflags)  $(HepMC_fflags)  $(CLHEP_fflags) 
use_pp_fflags=  $(RootIOTools_pp_fflags)  $(DataModelRelease_pp_fflags)  $(GenEventV2_pp_fflags)  $(SimEventV2_pp_fflags)  $(ElecEvent_pp_fflags)  $(RecEvent_pp_fflags)  $(ClusterInfoSvc_pp_fflags)  $(CalibEvent_pp_fflags)  $(ClusterInfoEvent_pp_fflags)  $(RootIOSvc_pp_fflags)  $(RootIOUtil_pp_fflags)  $(EvtNavigator_pp_fflags)  $(DataRegistritionSvc_pp_fflags)  $(PhyEvent_pp_fflags)  $(EDMUtil_pp_fflags)  $(Geometry_pp_fflags)  $(Identifier_pp_fflags)  $(JunoTimer_pp_fflags)  $(SniperRelease_pp_fflags)  $(DataBuffer_pp_fflags)  $(HelloWorld_pp_fflags)  $(PyDataStore_pp_fflags)  $(DummyAlg_pp_fflags)  $(RootWriter_pp_fflags)  $(SniperKernel_pp_fflags)  $(BaseEvent_pp_fflags)  $(CLHEPDict_pp_fflags)  $(Context_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(ROOT_pp_fflags)  $(HepMC_pp_fflags)  $(CLHEP_pp_fflags) 
use_libraries= $(DataModelRelease_libraries)  $(GenEventV2_libraries)  $(SimEventV2_libraries)  $(ElecEvent_libraries)  $(RecEvent_libraries)  $(ClusterInfoSvc_libraries)  $(CalibEvent_libraries)  $(ClusterInfoEvent_libraries)  $(RootIOSvc_libraries)  $(RootIOUtil_libraries)  $(EvtNavigator_libraries)  $(DataRegistritionSvc_libraries)  $(PhyEvent_libraries)  $(EDMUtil_libraries)  $(Geometry_libraries)  $(Identifier_libraries)  $(JunoTimer_libraries)  $(SniperRelease_libraries)  $(DataBuffer_libraries)  $(HelloWorld_libraries)  $(PyDataStore_libraries)  $(DummyAlg_libraries)  $(RootWriter_libraries)  $(SniperKernel_libraries)  $(BaseEvent_libraries)  $(CLHEPDict_libraries)  $(XmlObjDesc_libraries)  $(Context_libraries)  $(SniperPolicy_libraries)  $(Boost_libraries)  $(Python_libraries)  $(ROOT_libraries)  $(HepMC_libraries)  $(CLHEP_libraries) 
fincludes= $(includes)
RootIOTools_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_more_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
RootIOTools_python_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= RootIOTools install_more_includes RootIOTools_python 
all_constituents= $(constituents)
constituentsclean= RootIOTools_pythonclean install_more_includesclean RootIOToolsclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
RootIOToolsprototype_dependencies= $(RootIOToolscompile_dependencies)
